### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by mooreye** [sezero/quakespasm#41]
Please consider making quakespasm available on flathub.org
Currently there is no good way to install Quakespasm on Fedora.

**Comment by sezero** [comment]
I won't bother myself with flatpak or flathub.org:
- Fedora doesn't even distribute qs
- Building qs as a normal user and using it is super easy,
  so I don't see the need in installing it system-wide.

**Comment by Novum** [comment]
I think AppImages like vkQuake is a much better solution. Runs everywhere if you build them in an old enough Docker image.

**Comment by sezero** [comment]
I already build on old linux distros and release linux x86 and x86_64 tarballs and
they should run on every decent distro. I really don't see the need for any of this.

**Comment by Novum** [comment]
Might be true, not quite sure. Linux compatibility is a minefield.

**Comment by garhow** [comment]
I seriously hope you reconsider flatpak support for this project. Flatpak is currently the most reliable and accessible way to distribute software across every modern Linux distribution and is the easiest way to preserve software due to its dependency bundling and the freedesktop runtime that ensures compatibility. regarding your previous points:

> Fedora doesn't even distribute qs

**This.** This is why qs should be available on flathub, to ensure that it is easily accessible to every modern linux distro.

> Building qs as a normal user and using it is super easy, so I don't see the need in installing it system-wide.

For the everyday desktop linux user, **compiling software is not easy**, especially C software. Having to gather dependencies and figure out how to use makefiles and compilers is not easy for the average person who just wants to play quake. Also, you don't need to install flatpaks system-wide, they can be installed for specific user

> I already build on old linux distros and release linux x86 and x86_64 tarballs and they should run on every decent distro. I really don't see the need for any of this.

Sure, you may build for older linux distros and release tarballs, but this isn't as accessible as simply installing qs through flatpak and then opening it through the gui. Additionally, there is no quake engine available on flathub at the moment, and qs would fill in that gap very nicely
