### ISSUE TITLE
Fullbrights ignored on liquid surfaces

### ISSUE THREAD

**Issue by mankrip** [sezero/quakespasm#43]
Lava should always be fullbright because the lava texture is 100% made of fullbright colors. But the lightmaps are showing up on lava surfaces because the engine is not applying fullbright colors to liquid surfaces, as shown [in this YouTube video](https://www.youtube.com/watch?v=AmPB6wWOXbQ).

**Comment by sezero** [comment]
Do you have a patch?

**Comment by mankrip** [comment]
> 

Unfortunately no, or I'd have submitted it directly.

**Comment by sezero** [comment]
@ericwa, @andrei-drexler, @temx, @Novum: Any quick solutions?

**Comment by temx** [comment]
All of QS / QSS / FTE / Ironwail / vkQuake render this the same way so I don't think it's prudent to change it now. The lava textures I have (id1 *lava1 / *lava2) do have a mix of fullbright and non-fullbright pixels, so I suspect this wouldn't look as expected.

I believe this can be tweaked in the level compile tools so they give you fullbright lava if desired either by setting the lightmap to white (which would look as before but allow dlights to brighten it more) or by not marking the lava texture as lit.

**Comment by sezero** [comment]
Close as `WONTFIX` then?

**Comment by temx** [comment]
I think so, but while we're here, I've tested what happens if [some warp textures are marked as unlit and some are not](https://user-images.githubusercontent.com/24851409/199310200-29785d42-cf3d-4f49-84d5-e2fcc02f5cbd.png) (no current map compile tools do this as far as I'm aware). It works on QSS, FTE, Ironwail and vkQuake but not in Quakespasm since it assumes all are of the same type. I'm opening a PR in case you want to remedy that.

**Comment by Flecked42** [comment]
I believe mappers can already do that with the `_lightignore` key

**Comment by sezero** [comment]
PR #45 is in. Closing this ticket.
